/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Keychain-Access.h
 #	source generated by 4D Plugin Wizard
 #	Project : Keychain Access
 #	author : miyako
 #	2022/09/05
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_KEYCHAIN_ACCESS_H
#define PLUGIN_KEYCHAIN_ACCESS_H

#include "4DPluginAPI.h"

#include "json/json.h"
#include "support/4DPlugin-JSON.h"
#include <Security/Security.h>
#include <Cocoa/Cocoa.h>
#include "C_BLOB.h"

#pragma mark -

void Keychain_Search_items(PA_PluginParameters params);

#endif /* PLUGIN_KEYCHAIN_ACCESS_H */
